services:
  whistreaming:
    build: .
    command: --model=medium.en --language en --warmup-file samples/english.wav --web-port 5000
    #command: --model=xezpeleta/whisper-medium-eu-ct2 --language eu --warmup-file samples/basque.wav --web-port 5000
    #volumes:
    #  - .:/app/zuzeneko_whistreaminga
    ports:
      - "43007:43007"
      - "5000:5000"
      - "5001:5001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
